# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './regbank_reader_main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_regbank_reader_main(object):
    def setupUi(self, regbank_reader_main):
        regbank_reader_main.setObjectName(_fromUtf8("regbank_reader_main"))
        regbank_reader_main.resize(1017, 734)
        self.centralwidget = QtGui.QWidget(regbank_reader_main)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mainTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.mainTabWidget.setObjectName(_fromUtf8("mainTabWidget"))
        self.initializationTab = QtGui.QWidget()
        self.initializationTab.setObjectName(_fromUtf8("initializationTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.initializationTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.initializationTab)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.pushButton_targetConnect = QtGui.QPushButton(self.groupBox)
        self.pushButton_targetConnect.setMinimumSize(QtCore.QSize(261, 61))
        self.pushButton_targetConnect.setMaximumSize(QtCore.QSize(261, 61))
        self.pushButton_targetConnect.setObjectName(_fromUtf8("pushButton_targetConnect"))
        self.gridLayout_9.addWidget(self.pushButton_targetConnect, 0, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_9.addWidget(self.line_3, 0, 1, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_18 = QtGui.QLabel(self.groupBox)
        self.label_18.setMinimumSize(QtCore.QSize(0, 61))
        self.label_18.setMaximumSize(QtCore.QSize(130, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 0, 0, 1, 1)
        self.lineEdit_unique_id = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_unique_id.sizePolicy().hasHeightForWidth())
        self.lineEdit_unique_id.setSizePolicy(sizePolicy)
        self.lineEdit_unique_id.setMinimumSize(QtCore.QSize(261, 61))
        self.lineEdit_unique_id.setMaximumSize(QtCore.QSize(261, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_unique_id.setFont(font)
        self.lineEdit_unique_id.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_unique_id.setObjectName(_fromUtf8("lineEdit_unique_id"))
        self.gridLayout.addWidget(self.lineEdit_unique_id, 0, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox)
        self.label_19.setMinimumSize(QtCore.QSize(0, 61))
        self.label_19.setMaximumSize(QtCore.QSize(130, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 1, 0, 1, 1)
        self.lineEdit_unique_msg = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_unique_msg.sizePolicy().hasHeightForWidth())
        self.lineEdit_unique_msg.setSizePolicy(sizePolicy)
        self.lineEdit_unique_msg.setMinimumSize(QtCore.QSize(261, 61))
        self.lineEdit_unique_msg.setMaximumSize(QtCore.QSize(261, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_unique_msg.setFont(font)
        self.lineEdit_unique_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_unique_msg.setObjectName(_fromUtf8("lineEdit_unique_msg"))
        self.gridLayout.addWidget(self.lineEdit_unique_msg, 1, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.initializationTab)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.pushButton_loadRegBank = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_loadRegBank.setEnabled(False)
        self.pushButton_loadRegBank.setMinimumSize(QtCore.QSize(261, 61))
        self.pushButton_loadRegBank.setObjectName(_fromUtf8("pushButton_loadRegBank"))
        self.gridLayout_8.addWidget(self.pushButton_loadRegBank, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.mainTabWidget.addTab(self.initializationTab, _fromUtf8(""))
        self.regbankTab = QtGui.QWidget()
        self.regbankTab.setObjectName(_fromUtf8("regbankTab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.regbankTab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_3 = QtGui.QGroupBox(self.regbankTab)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 183))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(57, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setMinimumSize(QtCore.QSize(131, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setMinimumSize(QtCore.QSize(131, 41))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setMinimumSize(QtCore.QSize(131, 41))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.comboBox_loadedRegbankSel = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_loadedRegbankSel.setMinimumSize(QtCore.QSize(211, 40))
        self.comboBox_loadedRegbankSel.setObjectName(_fromUtf8("comboBox_loadedRegbankSel"))
        self.verticalLayout_3.addWidget(self.comboBox_loadedRegbankSel)
        self.comboBox_loadedSheetSel = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_loadedSheetSel.setMinimumSize(QtCore.QSize(211, 40))
        self.comboBox_loadedSheetSel.setObjectName(_fromUtf8("comboBox_loadedSheetSel"))
        self.verticalLayout_3.addWidget(self.comboBox_loadedSheetSel)
        self.comboBox_loadedRegisterSel = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_loadedRegisterSel.setMinimumSize(QtCore.QSize(211, 40))
        self.comboBox_loadedRegisterSel.setObjectName(_fromUtf8("comboBox_loadedRegisterSel"))
        self.verticalLayout_3.addWidget(self.comboBox_loadedRegisterSel)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        spacerItem1 = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(57, 40))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setMinimumSize(QtCore.QSize(121, 41))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_5.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setMinimumSize(QtCore.QSize(91, 41))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_5.addWidget(self.label_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.lineEdit_loadedCalcAddr = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_loadedCalcAddr.sizePolicy().hasHeightForWidth())
        self.lineEdit_loadedCalcAddr.setSizePolicy(sizePolicy)
        self.lineEdit_loadedCalcAddr.setMinimumSize(QtCore.QSize(201, 41))
        self.lineEdit_loadedCalcAddr.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_loadedCalcAddr.setObjectName(_fromUtf8("lineEdit_loadedCalcAddr"))
        self.verticalLayout_6.addWidget(self.lineEdit_loadedCalcAddr)
        self.lineEdit_loadedSheetAddr = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_loadedSheetAddr.sizePolicy().hasHeightForWidth())
        self.lineEdit_loadedSheetAddr.setSizePolicy(sizePolicy)
        self.lineEdit_loadedSheetAddr.setMinimumSize(QtCore.QSize(201, 41))
        self.lineEdit_loadedSheetAddr.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_loadedSheetAddr.setObjectName(_fromUtf8("lineEdit_loadedSheetAddr"))
        self.verticalLayout_6.addWidget(self.lineEdit_loadedSheetAddr)
        self.comboBox_loadedSheetOffsetSel = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_loadedSheetOffsetSel.setMinimumSize(QtCore.QSize(201, 41))
        self.comboBox_loadedSheetOffsetSel.setObjectName(_fromUtf8("comboBox_loadedSheetOffsetSel"))
        self.verticalLayout_6.addWidget(self.comboBox_loadedSheetOffsetSel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(72, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.regbankTab)
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.tabWidget_registers = QtGui.QTabWidget(self.groupBox_4)
        self.tabWidget_registers.setTabsClosable(True)
        self.tabWidget_registers.setObjectName(_fromUtf8("tabWidget_registers"))
        self.verticalLayout_8.addWidget(self.tabWidget_registers)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.mainTabWidget.addTab(self.regbankTab, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 136))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem3 = QtGui.QSpacerItem(57, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.pushButton_getCurrRegisterAddr = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_getCurrRegisterAddr.setMinimumSize(QtCore.QSize(0, 41))
        self.pushButton_getCurrRegisterAddr.setObjectName(_fromUtf8("pushButton_getCurrRegisterAddr"))
        self.verticalLayout_9.addWidget(self.pushButton_getCurrRegisterAddr)
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setMinimumSize(QtCore.QSize(0, 40))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_9.addWidget(self.label_8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.lineEdit_memEditorAddr = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_memEditorAddr.setMinimumSize(QtCore.QSize(211, 40))
        self.lineEdit_memEditorAddr.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_memEditorAddr.setObjectName(_fromUtf8("lineEdit_memEditorAddr"))
        self.verticalLayout_10.addWidget(self.lineEdit_memEditorAddr)
        self.comboBox_memEditorMode = QtGui.QComboBox(self.groupBox_5)
        self.comboBox_memEditorMode.setMinimumSize(QtCore.QSize(211, 40))
        self.comboBox_memEditorMode.setObjectName(_fromUtf8("comboBox_memEditorMode"))
        self.comboBox_memEditorMode.addItem(_fromUtf8(""))
        self.comboBox_memEditorMode.addItem(_fromUtf8(""))
        self.verticalLayout_10.addWidget(self.comboBox_memEditorMode)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem4 = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.pushButton_memEditorReadValue = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_memEditorReadValue.setMinimumSize(QtCore.QSize(211, 40))
        self.pushButton_memEditorReadValue.setObjectName(_fromUtf8("pushButton_memEditorReadValue"))
        self.verticalLayout_11.addWidget(self.pushButton_memEditorReadValue)
        self.pushButton_memEditorWriteValue = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_memEditorWriteValue.setMinimumSize(QtCore.QSize(211, 40))
        self.pushButton_memEditorWriteValue.setObjectName(_fromUtf8("pushButton_memEditorWriteValue"))
        self.verticalLayout_11.addWidget(self.pushButton_memEditorWriteValue)
        self.horizontalLayout_6.addLayout(self.verticalLayout_11)
        spacerItem5 = QtGui.QSpacerItem(72, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_15.addWidget(self.groupBox_5)
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_15.addWidget(self.line)
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 86))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem6 = QtGui.QSpacerItem(55, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_6)
        self.label_9.setMinimumSize(QtCore.QSize(0, 40))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.lineEdit_memEditorNextValue = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_memEditorNextValue.setMinimumSize(QtCore.QSize(211, 40))
        self.lineEdit_memEditorNextValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_memEditorNextValue.setObjectName(_fromUtf8("lineEdit_memEditorNextValue"))
        self.horizontalLayout_8.addWidget(self.lineEdit_memEditorNextValue)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        spacerItem7 = QtGui.QSpacerItem(56, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_15 = QtGui.QLabel(self.groupBox_6)
        self.label_15.setMinimumSize(QtCore.QSize(0, 40))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_7.addWidget(self.label_15)
        self.lineEdit_memEditorCurrValue = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_memEditorCurrValue.setMinimumSize(QtCore.QSize(211, 40))
        self.lineEdit_memEditorCurrValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_memEditorCurrValue.setReadOnly(True)
        self.lineEdit_memEditorCurrValue.setObjectName(_fromUtf8("lineEdit_memEditorCurrValue"))
        self.horizontalLayout_7.addWidget(self.lineEdit_memEditorCurrValue)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_7)
        spacerItem8 = QtGui.QSpacerItem(55, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.verticalLayout_15.addWidget(self.groupBox_6)
        self.groupBox_10 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.groupBox_byte_3 = QtGui.QGroupBox(self.groupBox_10)
        self.groupBox_byte_3.setObjectName(_fromUtf8("groupBox_byte_3"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.groupBox_byte_3)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.radioButton_31 = QtGui.QRadioButton(self.groupBox_byte_3)
        self.radioButton_31.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_31.setAutoExclusive(False)
        self.radioButton_31.setObjectName(_fromUtf8("radioButton_31"))
        self.horizontalLayout_14.addWidget(self.radioButton_31)
        self.radioButton_30 = QtGui.QRadioButton(self.groupBox_byte_3)
        self.radioButton_30.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_30.setAutoExclusive(False)
        self.radioButton_30.setObjectName(_fromUtf8("radioButton_30"))
        self.horizontalLayout_14.addWidget(self.radioButton_30)
        self.radioButton_29 = QtGui.QRadioButton(self.groupBox_byte_3)
        self.radioButton_29.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_29.setAutoExclusive(False)
        self.radioButton_29.setObjectName(_fromUtf8("radioButton_29"))
        self.horizontalLayout_14.addWidget(self.radioButton_29)
        self.radioButton_28 = QtGui.QRadioButton(self.groupBox_byte_3)
        self.radioButton_28.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_28.setAutoExclusive(False)
        self.radioButton_28.setObjectName(_fromUtf8("radioButton_28"))
        self.horizontalLayout_14.addWidget(self.radioButton_28)
        self.radioButton_27 = QtGui.QRadioButton(self.groupBox_byte_3)
        self.radioButton_27.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_27.setAutoExclusive(False)
        self.radioButton_27.setObjectName(_fromUtf8("radioButton_27"))
        self.horizontalLayout_14.addWidget(self.radioButton_27)
        self.radioButton_26 = QtGui.QRadioButton(self.groupBox_byte_3)
        self.radioButton_26.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_26.setAutoExclusive(False)
        self.radioButton_26.setObjectName(_fromUtf8("radioButton_26"))
        self.horizontalLayout_14.addWidget(self.radioButton_26)
        self.radioButton_25 = QtGui.QRadioButton(self.groupBox_byte_3)
        self.radioButton_25.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_25.setAutoExclusive(False)
        self.radioButton_25.setObjectName(_fromUtf8("radioButton_25"))
        self.horizontalLayout_14.addWidget(self.radioButton_25)
        self.radioButton_24 = QtGui.QRadioButton(self.groupBox_byte_3)
        self.radioButton_24.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_24.setAutoExclusive(False)
        self.radioButton_24.setObjectName(_fromUtf8("radioButton_24"))
        self.horizontalLayout_14.addWidget(self.radioButton_24)
        self.verticalLayout_12.addWidget(self.groupBox_byte_3)
        self.groupBox_byte_2 = QtGui.QGroupBox(self.groupBox_10)
        self.groupBox_byte_2.setObjectName(_fromUtf8("groupBox_byte_2"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.groupBox_byte_2)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.radioButton_23 = QtGui.QRadioButton(self.groupBox_byte_2)
        self.radioButton_23.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_23.setAutoExclusive(False)
        self.radioButton_23.setObjectName(_fromUtf8("radioButton_23"))
        self.horizontalLayout_12.addWidget(self.radioButton_23)
        self.radioButton_22 = QtGui.QRadioButton(self.groupBox_byte_2)
        self.radioButton_22.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_22.setAutoExclusive(False)
        self.radioButton_22.setObjectName(_fromUtf8("radioButton_22"))
        self.horizontalLayout_12.addWidget(self.radioButton_22)
        self.radioButton_21 = QtGui.QRadioButton(self.groupBox_byte_2)
        self.radioButton_21.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_21.setAutoExclusive(False)
        self.radioButton_21.setObjectName(_fromUtf8("radioButton_21"))
        self.horizontalLayout_12.addWidget(self.radioButton_21)
        self.radioButton_20 = QtGui.QRadioButton(self.groupBox_byte_2)
        self.radioButton_20.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_20.setAutoExclusive(False)
        self.radioButton_20.setObjectName(_fromUtf8("radioButton_20"))
        self.horizontalLayout_12.addWidget(self.radioButton_20)
        self.radioButton_19 = QtGui.QRadioButton(self.groupBox_byte_2)
        self.radioButton_19.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_19.setAutoExclusive(False)
        self.radioButton_19.setObjectName(_fromUtf8("radioButton_19"))
        self.horizontalLayout_12.addWidget(self.radioButton_19)
        self.radioButton_18 = QtGui.QRadioButton(self.groupBox_byte_2)
        self.radioButton_18.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_18.setAutoExclusive(False)
        self.radioButton_18.setObjectName(_fromUtf8("radioButton_18"))
        self.horizontalLayout_12.addWidget(self.radioButton_18)
        self.radioButton_17 = QtGui.QRadioButton(self.groupBox_byte_2)
        self.radioButton_17.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_17.setAutoExclusive(False)
        self.radioButton_17.setObjectName(_fromUtf8("radioButton_17"))
        self.horizontalLayout_12.addWidget(self.radioButton_17)
        self.radioButton_16 = QtGui.QRadioButton(self.groupBox_byte_2)
        self.radioButton_16.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_16.setAutoExclusive(False)
        self.radioButton_16.setObjectName(_fromUtf8("radioButton_16"))
        self.horizontalLayout_12.addWidget(self.radioButton_16)
        self.verticalLayout_12.addWidget(self.groupBox_byte_2)
        self.groupBox_byte_1 = QtGui.QGroupBox(self.groupBox_10)
        self.groupBox_byte_1.setObjectName(_fromUtf8("groupBox_byte_1"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.groupBox_byte_1)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.radioButton_15 = QtGui.QRadioButton(self.groupBox_byte_1)
        self.radioButton_15.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_15.setAutoExclusive(False)
        self.radioButton_15.setObjectName(_fromUtf8("radioButton_15"))
        self.horizontalLayout_11.addWidget(self.radioButton_15)
        self.radioButton_14 = QtGui.QRadioButton(self.groupBox_byte_1)
        self.radioButton_14.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_14.setAutoExclusive(False)
        self.radioButton_14.setObjectName(_fromUtf8("radioButton_14"))
        self.horizontalLayout_11.addWidget(self.radioButton_14)
        self.radioButton_13 = QtGui.QRadioButton(self.groupBox_byte_1)
        self.radioButton_13.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_13.setAutoExclusive(False)
        self.radioButton_13.setObjectName(_fromUtf8("radioButton_13"))
        self.horizontalLayout_11.addWidget(self.radioButton_13)
        self.radioButton_12 = QtGui.QRadioButton(self.groupBox_byte_1)
        self.radioButton_12.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_12.setAutoExclusive(False)
        self.radioButton_12.setObjectName(_fromUtf8("radioButton_12"))
        self.horizontalLayout_11.addWidget(self.radioButton_12)
        self.radioButton_11 = QtGui.QRadioButton(self.groupBox_byte_1)
        self.radioButton_11.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_11.setAutoExclusive(False)
        self.radioButton_11.setObjectName(_fromUtf8("radioButton_11"))
        self.horizontalLayout_11.addWidget(self.radioButton_11)
        self.radioButton_10 = QtGui.QRadioButton(self.groupBox_byte_1)
        self.radioButton_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_10.setAutoExclusive(False)
        self.radioButton_10.setObjectName(_fromUtf8("radioButton_10"))
        self.horizontalLayout_11.addWidget(self.radioButton_10)
        self.radioButton_9 = QtGui.QRadioButton(self.groupBox_byte_1)
        self.radioButton_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_9.setAutoExclusive(False)
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.horizontalLayout_11.addWidget(self.radioButton_9)
        self.radioButton_8 = QtGui.QRadioButton(self.groupBox_byte_1)
        self.radioButton_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_8.setAutoExclusive(False)
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.horizontalLayout_11.addWidget(self.radioButton_8)
        self.verticalLayout_12.addWidget(self.groupBox_byte_1)
        self.groupBox_byte_0 = QtGui.QGroupBox(self.groupBox_10)
        self.groupBox_byte_0.setObjectName(_fromUtf8("groupBox_byte_0"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupBox_byte_0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.radioButton_7 = QtGui.QRadioButton(self.groupBox_byte_0)
        self.radioButton_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_7.setAutoExclusive(False)
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.horizontalLayout_10.addWidget(self.radioButton_7)
        self.radioButton_6 = QtGui.QRadioButton(self.groupBox_byte_0)
        self.radioButton_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_6.setAutoExclusive(False)
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.horizontalLayout_10.addWidget(self.radioButton_6)
        self.radioButton_5 = QtGui.QRadioButton(self.groupBox_byte_0)
        self.radioButton_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_5.setAutoExclusive(False)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.horizontalLayout_10.addWidget(self.radioButton_5)
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox_byte_0)
        self.radioButton_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.horizontalLayout_10.addWidget(self.radioButton_4)
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox_byte_0)
        self.radioButton_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.horizontalLayout_10.addWidget(self.radioButton_3)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox_byte_0)
        self.radioButton_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.horizontalLayout_10.addWidget(self.radioButton_2)
        self.radioButton_1 = QtGui.QRadioButton(self.groupBox_byte_0)
        self.radioButton_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_1.setAutoExclusive(False)
        self.radioButton_1.setObjectName(_fromUtf8("radioButton_1"))
        self.horizontalLayout_10.addWidget(self.radioButton_1)
        self.radioButton_0 = QtGui.QRadioButton(self.groupBox_byte_0)
        self.radioButton_0.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_0.setAutoExclusive(False)
        self.radioButton_0.setObjectName(_fromUtf8("radioButton_0"))
        self.horizontalLayout_10.addWidget(self.radioButton_0)
        self.verticalLayout_12.addWidget(self.groupBox_byte_0)
        self.verticalLayout_15.addWidget(self.groupBox_10)
        self.mainTabWidget.addTab(self.tab, _fromUtf8(""))
        self.tibProcessorTab = QtGui.QWidget()
        self.tibProcessorTab.setObjectName(_fromUtf8("tibProcessorTab"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.tibProcessorTab)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.groupBox_9 = QtGui.QGroupBox(self.tibProcessorTab)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_27 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.pushButton_loadTibFile = QtGui.QPushButton(self.groupBox_9)
        self.pushButton_loadTibFile.setMinimumSize(QtCore.QSize(261, 61))
        self.pushButton_loadTibFile.setObjectName(_fromUtf8("pushButton_loadTibFile"))
        self.gridLayout_27.addWidget(self.pushButton_loadTibFile, 0, 0, 1, 1)
        self.gridLayout_28 = QtGui.QGridLayout()
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.pushButton_executeTib = QtGui.QPushButton(self.groupBox_9)
        self.pushButton_executeTib.setMinimumSize(QtCore.QSize(261, 61))
        self.pushButton_executeTib.setObjectName(_fromUtf8("pushButton_executeTib"))
        self.gridLayout_28.addWidget(self.pushButton_executeTib, 0, 0, 1, 1)
        self.comboBox_tibList = QtGui.QComboBox(self.groupBox_9)
        self.comboBox_tibList.setMinimumSize(QtCore.QSize(261, 61))
        self.comboBox_tibList.setObjectName(_fromUtf8("comboBox_tibList"))
        self.gridLayout_28.addWidget(self.comboBox_tibList, 0, 1, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_28, 1, 0, 1, 1)
        self.verticalLayout_14.addWidget(self.groupBox_9)
        self.groupBox_7 = QtGui.QGroupBox(self.tibProcessorTab)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.lineEdit_execTibCommand = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_execTibCommand.setMinimumSize(QtCore.QSize(0, 61))
        self.lineEdit_execTibCommand.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_execTibCommand.setObjectName(_fromUtf8("lineEdit_execTibCommand"))
        self.gridLayout_17.addWidget(self.lineEdit_execTibCommand, 0, 0, 1, 1)
        self.verticalLayout_14.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(self.tibProcessorTab)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.plainTextEdit_tibOutput = QtGui.QPlainTextEdit(self.groupBox_8)
        self.plainTextEdit_tibOutput.setMinimumSize(QtCore.QSize(921, 251))
        self.plainTextEdit_tibOutput.setReadOnly(True)
        self.plainTextEdit_tibOutput.setBackgroundVisible(False)
        self.plainTextEdit_tibOutput.setObjectName(_fromUtf8("plainTextEdit_tibOutput"))
        self.verticalLayout.addWidget(self.plainTextEdit_tibOutput)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButton_clearTibOutputs = QtGui.QPushButton(self.groupBox_8)
        self.pushButton_clearTibOutputs.setMinimumSize(QtCore.QSize(121, 40))
        self.pushButton_clearTibOutputs.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_clearTibOutputs.setObjectName(_fromUtf8("pushButton_clearTibOutputs"))
        self.horizontalLayout_4.addWidget(self.pushButton_clearTibOutputs)
        spacerItem9 = QtGui.QSpacerItem(505, 37, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_13.addLayout(self.verticalLayout)
        self.verticalLayout_14.addWidget(self.groupBox_8)
        self.groupBox_7.raise_()
        self.groupBox_8.raise_()
        self.groupBox_9.raise_()
        self.mainTabWidget.addTab(self.tibProcessorTab, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.mainTabWidget)
        regbank_reader_main.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(regbank_reader_main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1017, 29))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuRecording = QtGui.QMenu(self.menubar)
        self.menuRecording.setObjectName(_fromUtf8("menuRecording"))
        regbank_reader_main.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(regbank_reader_main)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        regbank_reader_main.setStatusBar(self.statusBar)
        self.actionLoad_Regbank = QtGui.QAction(regbank_reader_main)
        self.actionLoad_Regbank.setObjectName(_fromUtf8("actionLoad_Regbank"))
        self.actionExit = QtGui.QAction(regbank_reader_main)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(regbank_reader_main)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionStart = QtGui.QAction(regbank_reader_main)
        self.actionStart.setObjectName(_fromUtf8("actionStart"))
        self.actionStop = QtGui.QAction(regbank_reader_main)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuRecording.addAction(self.actionStart)
        self.menuRecording.addAction(self.actionStop)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRecording.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(regbank_reader_main)
        self.mainTabWidget.setCurrentIndex(0)
        self.tabWidget_registers.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(regbank_reader_main)

    def retranslateUi(self, regbank_reader_main):
        regbank_reader_main.setWindowTitle(_translate("regbank_reader_main", "MainWindow", None))
        self.groupBox.setTitle(_translate("regbank_reader_main", "Target Initialization", None))
        self.pushButton_targetConnect.setText(_translate("regbank_reader_main", "Connect", None))
        self.label_18.setText(_translate("regbank_reader_main", "Unique ID of target", None))
        self.lineEdit_unique_id.setText(_translate("regbank_reader_main", "0x00", None))
        self.label_19.setText(_translate("regbank_reader_main", "Unique MSG of target", None))
        self.lineEdit_unique_msg.setText(_translate("regbank_reader_main", "linux_pc", None))
        self.groupBox_2.setTitle(_translate("regbank_reader_main", "Regbank Initialization", None))
        self.pushButton_loadRegBank.setText(_translate("regbank_reader_main", "Load regbank excel", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.initializationTab), _translate("regbank_reader_main", "Initialization", None))
        self.groupBox_3.setTitle(_translate("regbank_reader_main", "Regbank Selection", None))
        self.label.setText(_translate("regbank_reader_main", "Select Regbank", None))
        self.label_2.setText(_translate("regbank_reader_main", "Select Sheet", None))
        self.label_3.setText(_translate("regbank_reader_main", "Select Register", None))
        self.label_6.setText(_translate("regbank_reader_main", "Calculated Address", None))
        self.label_4.setText(_translate("regbank_reader_main", "Sheet Base Address", None))
        self.label_5.setText(_translate("regbank_reader_main", "Sheet Offsets", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.regbankTab), _translate("regbank_reader_main", "Regbank", None))
        self.groupBox_5.setTitle(_translate("regbank_reader_main", "Initialization", None))
        self.pushButton_getCurrRegisterAddr.setText(_translate("regbank_reader_main", "Get Current Register (Addr)", None))
        self.label_8.setText(_translate("regbank_reader_main", "Editor Mode", None))
        self.comboBox_memEditorMode.setItemText(0, _translate("regbank_reader_main", "On Demand Mode", None))
        self.comboBox_memEditorMode.setItemText(1, _translate("regbank_reader_main", "Live Mode", None))
        self.pushButton_memEditorReadValue.setText(_translate("regbank_reader_main", "Read Value", None))
        self.pushButton_memEditorWriteValue.setText(_translate("regbank_reader_main", "Write Value", None))
        self.groupBox_6.setTitle(_translate("regbank_reader_main", "Memory Values", None))
        self.label_9.setText(_translate("regbank_reader_main", "Next Value / Edit Value", None))
        self.label_15.setText(_translate("regbank_reader_main", "Current Value", None))
        self.groupBox_10.setTitle(_translate("regbank_reader_main", "Memory Bytes Edit", None))
        self.groupBox_byte_3.setTitle(_translate("regbank_reader_main", "Bits [31:24]", None))
        self.radioButton_31.setText(_translate("regbank_reader_main", "Bit &7 :", None))
        self.radioButton_30.setText(_translate("regbank_reader_main", "Bit &6 :", None))
        self.radioButton_29.setText(_translate("regbank_reader_main", "Bit &5 :", None))
        self.radioButton_28.setText(_translate("regbank_reader_main", "Bit &4 :", None))
        self.radioButton_27.setText(_translate("regbank_reader_main", "Bit &3 :", None))
        self.radioButton_26.setText(_translate("regbank_reader_main", "Bit &2 :", None))
        self.radioButton_25.setText(_translate("regbank_reader_main", "Bit &1 :", None))
        self.radioButton_24.setText(_translate("regbank_reader_main", "Bit &0 :", None))
        self.groupBox_byte_2.setTitle(_translate("regbank_reader_main", "Bits [23:16]", None))
        self.radioButton_23.setText(_translate("regbank_reader_main", "Bit 7 :", None))
        self.radioButton_22.setText(_translate("regbank_reader_main", "Bit 6 :", None))
        self.radioButton_21.setText(_translate("regbank_reader_main", "Bit 5 :", None))
        self.radioButton_20.setText(_translate("regbank_reader_main", "Bit 4 :", None))
        self.radioButton_19.setText(_translate("regbank_reader_main", "Bit 3 :", None))
        self.radioButton_18.setText(_translate("regbank_reader_main", "Bit 2 :", None))
        self.radioButton_17.setText(_translate("regbank_reader_main", "Bit 1 :", None))
        self.radioButton_16.setText(_translate("regbank_reader_main", "Bit 0 :", None))
        self.groupBox_byte_1.setTitle(_translate("regbank_reader_main", "Bits [15:8]", None))
        self.radioButton_15.setText(_translate("regbank_reader_main", "Bit 7 :", None))
        self.radioButton_14.setText(_translate("regbank_reader_main", "Bit 6 :", None))
        self.radioButton_13.setText(_translate("regbank_reader_main", "Bit 5 :", None))
        self.radioButton_12.setText(_translate("regbank_reader_main", "Bit 4 :", None))
        self.radioButton_11.setText(_translate("regbank_reader_main", "Bit 3 :", None))
        self.radioButton_10.setText(_translate("regbank_reader_main", "Bit 2 :", None))
        self.radioButton_9.setText(_translate("regbank_reader_main", "Bit 1 :", None))
        self.radioButton_8.setText(_translate("regbank_reader_main", "Bit 0 :", None))
        self.groupBox_byte_0.setTitle(_translate("regbank_reader_main", "Bits [7:0]", None))
        self.radioButton_7.setText(_translate("regbank_reader_main", "Bit 7 :", None))
        self.radioButton_6.setText(_translate("regbank_reader_main", "Bit 6 :", None))
        self.radioButton_5.setText(_translate("regbank_reader_main", "Bit 5 :", None))
        self.radioButton_4.setText(_translate("regbank_reader_main", "Bit 4 :", None))
        self.radioButton_3.setText(_translate("regbank_reader_main", "Bit 3 :", None))
        self.radioButton_2.setText(_translate("regbank_reader_main", "Bit 2 :", None))
        self.radioButton_1.setText(_translate("regbank_reader_main", "Bit 1 :", None))
        self.radioButton_0.setText(_translate("regbank_reader_main", "Bit 0 :", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab), _translate("regbank_reader_main", "Memory Editor", None))
        self.groupBox_9.setTitle(_translate("regbank_reader_main", "TIB Initialization", None))
        self.pushButton_loadTibFile.setText(_translate("regbank_reader_main", "Load TIB file", None))
        self.pushButton_executeTib.setText(_translate("regbank_reader_main", "Execute Selected Tib", None))
        self.groupBox_7.setTitle(_translate("regbank_reader_main", "Enter TIB\'s", None))
        self.lineEdit_execTibCommand.setText(_translate("regbank_reader_main", ">>>", None))
        self.groupBox_8.setTitle(_translate("regbank_reader_main", "TIB Commands Output", None))
        self.pushButton_clearTibOutputs.setText(_translate("regbank_reader_main", "Clear Outputs", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tibProcessorTab), _translate("regbank_reader_main", "TIB Processor", None))
        self.menuFile.setTitle(_translate("regbank_reader_main", "Fi&le", None))
        self.menuHelp.setTitle(_translate("regbank_reader_main", "Help", None))
        self.menuRecording.setTitle(_translate("regbank_reader_main", "Recor&ding", None))
        self.actionLoad_Regbank.setText(_translate("regbank_reader_main", "Load Regbank", None))
        self.actionExit.setText(_translate("regbank_reader_main", "&Exit", None))
        self.actionAbout.setText(_translate("regbank_reader_main", "&About", None))
        self.actionStart.setText(_translate("regbank_reader_main", "&Start", None))
        self.actionStop.setText(_translate("regbank_reader_main", "St&op", None))

